name: Chell
on:
   push:
    branches: [ "main" ]
jobs:
  hemy:
    runs-on: ubuntu-latest

    steps:
      - name: hellcat
        id: scatpack
        run: echo a=a >> $GITHUB_OUTPUT
      - name: hellcat2
        run: echo ${{steps.scatpack.outputs.a}}
          

