name: rrt
  
on: [push]

jobs: 
 my_test:
    runs_on: ubuntu-latest
     steps:
      - name: cat
        id: fff
        run: echo a=a >> $GITHUB_OUTPUT

      - name: ham
        run: echo ${{steps.fff.outputs.a}}
    

 
